### PR TITLE
Fixes #45: Adapt to List<List<Integer>> for User.answers

### LINKED ISSUE #45: [Fix 0B - 1] Fix Conflicts caused by `User.answers`
Currently, since User.answers is a `List<Set<Integer>>` which is a nested structure, firebase refuses to upload it, causing issues. 

My thoughts:
1. Create a `DatabaseUser extends User`
2. Make `answers` in `DatabaseUser` a `List<String>`
3. Override getters and setters for `DatabaseUser`
5. Provide conversions between `User` and `FirebaseUser`

### PR DESCRIPTION
**Pull request by LanceLi1416**
# Description

Fixes #45 

I have adapted existing code using `User.answers` to use `List<List<Integer>>` to avoid issues. 

Please inform me if there are parts I forgot to modify. 

# Checklist

- [x] My PR does not contain unrelated files that may cause conflicts
- [x] I have performed a self-review of my own code
- [x] I have commented my code with javadoc and perhaps in-line comments (particularly in
  hard-to-understand areas)
- [x] My changes generate no new warnings or errors
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have not violated clean architecture principles
- [x] I have opted to use the most general form of datastructures (example: use `List` instead of
  `ArrayList` wherever possible)

### CODE REVIEW

**Review by MilenaMijuskovic — APPROVED** [review]

**Review by helen-li — DISMISSED** [review]
Looks good thanks for the quick changes!

**Review by nicholaspoon03 — APPROVED** [review]
The GenerateCompatibilityList change looks good to me! Thank you for your help, Lance!

**Review by rsrinivasan1 — APPROVED** [review]
Looks good after the small change to convert to ArrayList methods!

**Review by nicholaspoon03 — APPROVED** [review]
Changes look good to me!

**Review by helen-li — APPROVED** [review]

**Pull request merged**
