### PR TITLE
Finishes #83: Add Profile Image for Recommendation Feed

### LINKED ISSUE #83: [Feature 5C E01] Display Profile Image on Recommendation Profile
Adds diaplsy for profile image on recommendation profile instead of having a white space.

### PR DESCRIPTION
**Pull request by LanceLi1416**
# Description

Fixes #83

Now the recommendation view can display profile images. 

With profile image

Without profile image

# Checklist

- [x] My PR does not contain unrelated files that may cause conflicts
- [x] I have performed a self-review of my own code
- [x] I have commented my code with javadoc and perhaps in-line comments (particularly in
  hard-to-understand areas)
- [x] My changes generate no new warnings or errors
~- [] I have added tests that prove my fix is effective or that my feature works~
- [x] I have not violated clean architecture principles
- [x] I have opted to use the most general form of datastructures (example: use `List` instead of
  `ArrayList` wherever possible)

### CODE REVIEW

**Review by nicholaspoon03 — COMMENTED** [review]
Looks good, Lance! Thanks fo the hard work! Just make sure to fix the merge conflicts before merging pls

**Review by chloe2407 — APPROVED** [review]
looks great lance! thanks for adding an example picture of what the default and example profile would look like

**Review by nicholaspoon03 — APPROVED** [review]
Thanks for the quick fix, Lance!

**Review by swaner2 — APPROVED** [review]
noice

**Pull request merged**
