### PR TITLE
Feature 0A Update Project Structure - Complete

### PR DESCRIPTION
**Pull request by LanceLi1416**
Please make sure you have tested everything in [this PDF file](https://github.com/CSC207-2022F-UofT/course-project-group-80/files/9856272/Project.Initialization.pdf) (file is also on discord). If there are no errors, vote a yes, otherwise please send me a **complete copy** of your error message so I can make patches.

### CODE REVIEW

**Review by helen-li — APPROVED** [review]
Works & looks amazing to me! Especially love the git ignore setup so that we (hopefully) don't contaminate main with individual env files throughout the upcoming development process. Big props to you @LanceLi1416!

PS: Might need to consult teaching team on their Actions setup?

**Comment by LanceLi1416** [comment]
> Works & looks amazing to me! Especially love the git ignore setup so that we (hopefully) don't contaminate main with individual env files throughout the upcoming development process. Big props to you @LanceLi1416!
> 
> PS: Might need to consult teaching team later on their Actions setup?

Yes. I asked our TA today, amd she said we can try to figure out Github Action with her later if the automated testings fail completely (which is happening now).

**Review by swaner2 — APPROVED** [review]

**Review by VG2800 — APPROVED** [review]

**Review by MilenaMijuskovic — APPROVED** [review]
Nice!

**Review by chloe2407 — APPROVED** [review]

**Review by rsrinivasan1 — APPROVED** [review]
Project builds and runs as expected! Great work @LanceLi1416! 

Quick question: I noticed the project structure doesn't exactly match the outline on the original issue. Is this something you decided to change slightly?

**Comment by LanceLi1416** [comment]
> Quick question: I noticed the project structure doesn't exactly match the outline on the original issue. Is this something you decided to change slightly?

@rsrinivasan1 If you are talking about the lib folder under `app` and some additional resource files under the `res` folder, yes those are some modifications I made. If not please tell me where the difference is so I can take a closer look. Thank you!

**Pull request merged**
