### PR TITLE
Refactored user score usage

### PR DESCRIPTION
**Pull request by rsrinivasan1**
Introduced ```UserScoreInterface``` that the ```UserScoreFacade``` implements in order to maintain the Facade design pattern structure without overextending the duties of the ```UserScoreFacade``` class.

Refactored all previous instances of ```UserScoreFacade```.

P.S. Also includes a quick bug fix to remove unnecessary options in the academic questionnaire UI. 

# Checklist

- [x] My PR does not contain unrelated files that may cause conflicts
- [x] I have performed a self-review of my own code
- [x] I have commented my code with javadoc and perhaps in-line comments (particularly in
  hard-to-understand areas)
- [x] My changes generate no new warnings or errors
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have not violated clean architecture principles
- [x] I have opted to use the most general form of datastructures (example: use `List` instead of
  `ArrayList` wherever possible)

### CODE REVIEW

**Review by MilenaMijuskovic — DISMISSED** [review]
Nice!

**Review by chloe2407 — DISMISSED** [review]
Good work Raghav! Thanks for refactoring UserScoreFacade with an interface

**Review by nicholaspoon03 — CHANGES_REQUESTED** [review]
Just a quick question, so UserScoreFacade is instantiated in GenerateCompatibilityList. So how will this change that? I also don't understand the point of this interface if no one is calling this interface. You could create a static method for creating a UserScoreFacade however like this:
``public UserScoreFacade createUserScoreFacade(User user) {
    return new UserScoreFacade(user)
}``

**Comment by rsrinivasan1** [comment]
> Just a quick question, so UserScoreFacade is instantiated in GenerateCompatibilityList. So how will this change that? I also don't understand the point of this interface if no one is calling this interface. You could create a static method for creating a UserScoreFacade however like this: `public UserScoreFacade createUserScoreFacade(User user) { return new UserScoreFacade(user) }`

Since ```UserScoreFacade``` implements the ```UserScoreInterface```, we can simply instantiate the ```UserScoreInterface``` object with the facade class.

**Review by chloe2407 — APPROVED** [review]

**Review by nicholaspoon03 — APPROVED** [review]

**Pull request merged**
