### PR TITLE
Pull Request Template

### PR DESCRIPTION
**Pull request by helen-li**
Introducing a PR template for better quality control and clearer pull request descriptions in the future.

### CODE REVIEW

**Review by LanceLi1416 — DISMISSED** [review]
Thank you for the template Helen! This will certain make things more organized and easier to review~

**Comment by LanceLi1416** [comment]
Update: @helen-li sorry I just added a few things ~(>_<)~.

**Comment by helen-li** [comment]
> Update: @helen-li sorry I just added a few things ~(>_<)~.

No worries! Thanks for adding the example markdown syntax - it will be super helpful to anyone who might not be as familiar with it - that totally slipped my mind.

**Review by LanceLi1416 — APPROVED** [review]

**Review by nicholaspoon03 — APPROVED** [review]
Thank you Helen for taking the time to create this checklist. It will definitely improve efficiency by giving authors specific things to look for to ensure that their code is ready for a PR. Ultimately, this will reduce the amount of time that is required to approve PRs.

**Review by VG2800 — APPROVED** [review]
Thank you for the template Helen!

**Pull request merged**
